#!/bin/bash

host=$(/sbin/e-smith/config getprop nextcloud VirtualHost)

if [ -z "$host" ]; then
    echo "nextcloud: no VirtualHost defined."
    exit 1
fi

NC_CONF=/var/lib/nethserver/agent/nextcloud.json

if [ ! -f $NC_CONF ]; then
    echo "$NC_CONF not found. Run nextcloud-export first."
    exit 1
else
    response=$(cat $NC_CONF)
fi

# Read rsync configuration
user=$(echo $response | jq -r .data.output.credentials[0])
password=$(echo $response | jq -r .data.output.credentials[1])
address=$(echo $response | jq -r .data.output.address)
port=$(echo $response | jq -r .data.output.port)

# Terminate the rsync server
RSYNC_PASSWORD=$password rsync /dev/null rsync://$user@$address:$port/terminate 2>/dev/null

rm -f $NC_CONF

domain=$(/sbin/e-smith/config getprop sssd Realm | tr '[:upper:]' '[:lower:]')

echo Launch configure-module... # ////

ns8-action module/$user configure-module '{"host": "'$host'", "lets_encrypt": false, "http2https": true, "domain": "'$domain'"}'

if [ $? -gt 0 ]; then
    echo "ns8-action configure-module has timed out"
    exit 1
fi

echo Configure-module completed # ////
