#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

source /etc/nethserver/agent.env
source "${AGENT_STATE_DIR}"/agent.env
source "${AGENT_STATE_DIR}"/environment
cd "${AGENT_STATE_DIR}/nethserver-nextcloud"
source bind.env

# Assert required vars are set
: "${RSYNC_ENDPOINT:?}" "${RSYNC_PASSWORD:?}"
export RSYNC_PASSWORD

# Sync files with uid:gid mapping
rsync -i --times --recursive --owner --group --usermap=1-1000:82 --groupmap=1-1000:82 --delete --exclude=appdata\* --exclude=nextcloud.log /var/lib/nethserver/nextcloud/ "${RSYNC_ENDPOINT}"/data/volumes/nextcloud-app-data/data/

# Create database dump
mysqldump -S /run/rh-mariadb105-mariadb/nextcloud-mysql.sock nextcloud > /var/lib/nethserver/nextcloud/dump.sql
rsync -iz  --times --recursive --remove-source-files /var/lib/nethserver/nextcloud/dump.sql "${RSYNC_ENDPOINT}"/data/state/restore/

# Copy original config
rsync -i --times /usr/share/nextcloud/config/config.php "${RSYNC_ENDPOINT}"/data/state/config.php

if [[ "${MIGRATE_ACTION}" != "finish" ]]; then
    exit 0
fi

# Fallback to virtualhost prop value, if no input was given
if [[ -z "${NEXTCLOUD_VHOST}" ]]; then
    NEXTCLOUD_VHOST="$(/sbin/e-smith/config getprop nextcloud VirtualHost)"
fi

# Assert required vars are set
: "${NEXTCLOUD_VHOST:?}" "${IMPORT_TASK_ID:?}" "${USER_DOMAIN:?}"

# Stop and disable local Nextcloud Maria DB service
/sbin/e-smith/config setprop rh-mariadb105-mariadb@nextcloud status disabled || :
systemctl disable --now rh-mariadb105-mariadb@nextcloud || :

# Set up web redirects
mkdir -vp webroot
cat - >webroot/index.html <<EOF
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Nextcloud Migration</title>
  </head>
  <body>
    <h1>Nextcloud Migration</h1>
    <p>Site has moved to &#9758; <a href="https://${NEXTCLOUD_VHOST}">${NEXTCLOUD_VHOST}</a></p>
  </body>
</html>
EOF
/sbin/e-smith/expand-template /etc/httpd/conf.d/00ns8migration.conf
httpd -k graceful

# Commit Webtop migration
rsync "${RSYNC_ENDPOINT}"/terminate

# Wait until the import-module task has completed
ns8-action --attach wait "${IMPORT_TASK_ID}"

ns8-action --attach "module/${MODULE_INSTANCE_ID}" configure-module "$(
    jq -n -c \
    --arg hostname "${NEXTCLOUD_VHOST}" \
    --arg domain "${USER_DOMAIN}" \
    '{
        "host": $hostname,
        "lets_encrypt": false,
        "http2https": true,
        "domain": $domain
    }')"
