#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# read json from stdin
migration_config=$(cat /dev/stdin)
if [[ "$migration_config" != "null" ]]; then
    # read virtual host from migration configuration
    host=$(echo $migration_config | jq -r '.virtualHost')
fi

if [ -z "$host" ]; then
    # read virtual host from nextcloud configuration
    host=$(/sbin/e-smith/config getprop nextcloud VirtualHost)

    if [ -z "$host" ]; then
        echo "nextcloud: no VirtualHost defined."
        exit 1
    fi
fi

NC_CONF=/var/lib/nethserver/agent/nextcloud.json

if [ ! -f $NC_CONF ]; then
    echo "$NC_CONF not found. Run nextcloud-export first."
    exit 1
else
    response=$(cat $NC_CONF)
fi

# Read rsync configuration
user=$(echo $response | jq -r .data.output.credentials[0])
password=$(echo $response | jq -r .data.output.credentials[1])
address=$(echo $response | jq -r .data.output.address)
port=$(echo $response | jq -r .data.output.port)

# Terminate the rsync server
RSYNC_PASSWORD=$password rsync /dev/null rsync://$user@$address:$port/terminate 2>/dev/null

rm -f $NC_CONF

domain=$(/sbin/e-smith/config getprop sssd Realm | tr '[:upper:]' '[:lower:]')

ns8-action module/$user configure-module '{"host": "'$host'", "lets_encrypt": false, "http2https": true, "domain": "'$domain'"}'

if [ $? -gt 0 ]; then
    echo "ns8-action configure-module has timed out"
    exit 1
fi
