#!/usr/bin/perl -w
#
# Copyright (C) 2022 Nethesis S.r.l.
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);

#
# nethserver-ns8-migration-update event
#

my $event = 'nethserver-ns8-migration-update';

event_actions($event, qw(
    initialize-default-databases 00
    nethserver-ns8-migration-conf 20
));

#
# nethserver-ns8-migration-save event
#

$event = "nethserver-ns8-migration-save";

event_templates($event,
   '/etc/wireguard/wg0.conf'
);

event_services($event, qw(
    wg-quick@wg0 restart
    agent restart
));

#
# nethserver-ns8-migration-export-app event
#

my $event = 'nethserver-ns8-migration-export-app';

event_actions($event, qw(
   nethserver-ns8-migration-export-app-action 20
));

#
# nethserver-ns8-migration-migrate-app event
#

my $event = 'nethserver-ns8-migration-migrate-app';

event_actions($event, qw(
   nethserver-ns8-migration-migrate-app-action 20
));
