#!/usr/bin/perl -w
#
# Copyright (C) 2022 Nethesis S.r.l.
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);

#
# nethserver-ns8-migration-update event
#

my $event = 'nethserver-ns8-migration-update';

event_actions($event, qw(
    initialize-default-databases 00
));

event_templates($event, qw(
    /etc/httpd/conf.d/00ns8migration.conf
));

event_services($event, qw(
    httpd reload
));

#
# nethserver-ns8-migration-save event
#

$event = "nethserver-ns8-migration-save";

event_templates($event, qw(
    /etc/wireguard/ns8.conf
    /etc/httpd/conf.d/00ns8migration.conf
));

event_services($event, qw(
    wg-quick@ns8 restart
    httpd reload
));

#
# interface-update event
#

$event = "interface-update";

event_services($event, qw(
    wg-quick@ns8 try-restart
));
