#!/bin/bash

#
# Build NS8 agent and NS7 UI
#

set -e

# Build UI
NODE_OPTIONS="--openssl-legacy-provider"
export NODE_OPTIONS
pushd ui
npm install
npm run build
popd

tar -C ui/dist -c -z -f nethserver-ns8-migration-cockpit.tar.gz .
