#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

if [ -f /var/lib/nethserver/nethserver-ns8-migration/account-provider/ad/bind.env ]; then
    source /var/lib/nethserver/nethserver-ns8-migration/account-provider/ad/bind.env
    /usr/sbin/ns8-action module/$MODULE_INSTANCE_ID get-defaults '{"provision": "new-domain"}' | jq -r '.data.output.ipaddress_list // empty'
fi
