#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

source /etc/nethserver/agent.env
source "${AGENT_STATE_DIR}"/agent.env
source "${AGENT_STATE_DIR}"/environment
cd "${AGENT_STATE_DIR}/nethserver-webtop5"
source bind.env

# Ensure endpoint is defined
: ${RSYNC_ENDPOINT:?}


# XXX sync commands


if [[ "${MIGRATE_ACTION}" != "finish" ]]; then
    exit 0
fi

# Stop and disable local Webtop services
for service in tomcat8@webtop; do
    /sbin/e-smith/config setprop "${service}" status disabled || :
    systemctl disable --now "${service}" || :
done

: ${WEBTOP_VHOST:?}
export RSYNC_PASSWORD

# Commit Webtop migration
rsync "${RSYNC_ENDPOINT}"/terminate
