#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

scripts_dir="/usr/share/nethesis/nethserver-ns8-migration/apps/account-provider"
account_provider_type=$(/sbin/e-smith/config getprop sssd Provider)

script_file="${scripts_dir}/migrate-${account_provider_type}"
if [[ -x "${script_file}" ]]; then
    # Prepare script runtime environment
    mkdir -vp /var/lib/nethserver/agent/state/account-provider
    cd /var/lib/nethserver/agent/state/account-provider
    export MIGRATE_ACTION
    MIGRATE_ACTION=commit-data
    exec "${script_file}" "${@}"
else
    echo "[ERROR]  account provider type ${account_provider_type}" 1>&2
    exit 2
fi
