#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

# read list-modules.json
JSON_FILE="/var/lib/nethserver/nethserver-ns8-migration/list-modules.json"

# Check if nethvoice-proxy > 0 on the node
is_installed=$(jq -r --argjson node_id "$MODULE_NODE_ID" '
  .[] | select(.id == "nethvoice-proxy") | .install_destinations[] | select(.node_id == $node_id) | .instances > 0
' "$JSON_FILE")

# if not installed in the node, install first nethvoice-proxy
if [[ "$is_installed" == "false" ]]; then
     ns8-action --attach cluster add-module "$(printf '{"image": "nethvoice-proxy", "node": %d}' "${MODULE_NODE_ID}")"
fi

ns8-bind-app nethserver-nethvoice14
