#!/bin/bash

# Translate host name to IP address: it's more likely NS8 cluster will be able to connect to it
host=$(dig +short $(perl -MNethServer::SSSD -e 'print NethServer::SSSD->new()->host;'))
port=$(perl -MNethServer::SSSD -e 'print NethServer::SSSD->new()->port;')
basedn=$(perl -MNethServer::SSSD -e 'print NethServer::SSSD->new()->baseDN;')
binddn=$(/sbin/e-smith/config getprop sssd BindDN)
bindpass=$(/sbin/e-smith/config getprop sssd BindPassword)
domain=$(/sbin/e-smith/config getprop sssd Realm | tr '[:upper:]' '[:lower:]')
islocal=$(perl -MNethServer::SSSD -e 'print NethServer::SSSD->new()->isLocalProvider;')

provider=$(/sbin/e-smith/config getprop sssd Provider)
if [ "$provider" == "ad" ]; then
    schema="ad"
else
    schema="rfc2307"
fi
tls="true"
tls_verify="false"

# Add route to nsdc
if [[ "$schema" == "ad" && "$islocal" == "1" ]]; then
    remote=$(/sbin/e-smith/config getprop wg-quick@wg0 RemoteNetwork)
    greenip=$(perl -Mesmith::NetworksDB -e '$ndb = esmith::NetworksDB->open_ro(); print($ndb->green->prop("ipaddr"))')
    mkdir -p /etc/e-smith/templates-custom/var/lib/machines/nsdc/etc/systemd/network/green.network
    echo -e "[Route]\nDestination=$remote\nGateway=$greenip" > /etc/e-smith/templates-custom/var/lib/machines/nsdc/etc/systemd/network/green.network/20wg
    /sbin/e-smith/expand-template /var/lib/machines/nsdc/etc/systemd/network/green.network
    systemctl restart nsdc
fi

# Setup routes
source /var/lib/nethserver/agent/environment
green_net=$(perl -Mesmith::NetworksDB -Mesmith::util -e '$ndb = esmith::NetworksDB->open_ro(); $g=$ndb->green; print(esmith::util::computeLocalNetworkShortSpec($g->prop("ipaddr"), $g->prop("netmask")))')
ns8-action cluster update-routes '{"add": [{"network": "'$green_net'", "node_id": '$NODE_ID'}]}'

data='{"domain": "'$domain'", "protocol": "ldap", "host": "'$host'", "port": '$port', "schema": "'$schema'", "bind_dn": "'$binddn'", "base_dn": "'$basedn'", "bind_password": "'$bindpass'", "tls": true, "tls_verify": false}'

ns8-action cluster add-external-domain "$data"
