#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

source /etc/nethserver/agent.env
source "${AGENT_STATE_DIR}"/agent.env
source "${AGENT_STATE_DIR}"/environment
cd "${AGENT_STATE_DIR}/nethserver-mail"
source bind.env

migrate_deps ()
{
    if [[ -f "${AGENT_STATE_DIR}/nethserver-webtop5/bind.env" ]]; then
        command "${AGENT_INSTALL_DIR}/apps/nethserver-webtop5/migrate"
    fi

    if [[ -f "${AGENT_STATE_DIR}/nethserver-roundcubemail/bind.env" ]]; then
        command "${AGENT_INSTALL_DIR}/apps/nethserver-roundcubemail/migrate"
    fi
}

hostname -d > mail_domain.txt
echo "${USER_DOMAIN:?}" > user_domain.txt

/sbin/e-smith/db domains printjson > domains.json
/sbin/e-smith/db accounts printjson > accounts.json
/sbin/e-smith/config printjson postfix > postfix.json
/sbin/e-smith/config printjson dovecot > dovecot.json
/sbin/e-smith/config printjson rspamd > rspamd.json

# Ensure endpoint is defined
: ${RSYNC_ENDPOINT:?}
export RSYNC_PASSWORD

# Ensure module ID is defined, and export it for Webtop5
: ${MODULE_INSTANCE_ID:?}
export MAIL_INSTANCE_ID="${MODULE_INSTANCE_ID}"

# Send configuration files
rsync -i --remove-source-files user_domain.txt mail_domain.txt {domains,accounts,postfix,dovecot,rspamd}.json "${RSYNC_ENDPOINT}"/data/state/

if [[ "${MIGRATE_ACTION}" == "finish" ]]; then
    # During the last, "finish" rsync run there must be no changes to
    # contents of maildirs: stop the services early.
    systemctl stop postfix dovecot rspamd
fi

# rsync note: using usermap and groupmap arguments because the chown does
# not work. Using the "catchall" range 1-1000 because "*" does not work

# Send mailboxes
rsync -i --archive --usermap=1-1000:100 --groupmap=1-1000:101 --delete /var/lib/nethserver/vmail/ "${RSYNC_ENDPOINT}"/data/volumes/dovecot-data/

# Send Redis database, the import-module will rename it properly
if [[ -f /var/lib/redis/rspamd/dump.rdb ]]; then
    rsync -i --archive --usermap=1-1000:100 --groupmap=1-1000:101 /var/lib/redis/rspamd/dump.rdb "${RSYNC_ENDPOINT}"/data/volumes/rspamd-redis/dump.rdb
fi

# Overwrite default DKIM key
rsync -i --archive --usermap=1-1000:101 --groupmap=1-1000:102 /etc/opendkim/keys/default.private "${RSYNC_ENDPOINT}"/data/volumes/rspamd-data/dkim/default.key
rsync -i --archive --usermap=1-1000:101 --groupmap=1-1000:102 /etc/opendkim/keys/default.txt "${RSYNC_ENDPOINT}"/data/volumes/rspamd-data/dkim/default.txt

if [[ "${MIGRATE_ACTION}" != "finish" ]]; then
    migrate_deps
    exit 0
fi

# Stop and disable local Mail services
for service in rspamd postfix dovecot opendkim olefy; do
    /sbin/e-smith/config setprop "${service}" status disabled || :
    systemctl disable --now "${service}" || :
done

# Commit Mail migration
rsync "${RSYNC_ENDPOINT}"/terminate

# Wait until the import-module task has completed
ns8-action --attach wait "${IMPORT_TASK_ID}"

migrate_deps
