#!/bin/bash

exec &>> /var/log/ns8-migration.log

host=$(/sbin/e-smith/config getprop mattermost VirtualHost)

if [ -z "$host" ]; then
    echo "mattermost: no VirtualHost defined."
    exit 1
fi

MM_CONF=/var/lib/nethserver/agent/mattermost.json

if [ ! -f $MM_CONF ]; then
    echo "$MM_CONF not found. Run mattermost-export first."
    exit 1
else
    response=$(cat $MM_CONF)
fi

# Read rsync configuration
user=$(echo $response | jq -r .data.output.credentials[0])
password=$(echo $response | jq -r .data.output.credentials[1])
address=$(echo $response | jq -r .data.output.address)
port=$(echo $response | jq -r .data.output.port)

# Terminate the rsync server
RSYNC_PASSWORD=$password rsync /dev/null rsync://$user@$address:$port/terminate 2>/dev/null

rm -f $MM_CONF

ns8-action module/$user configure-module '{"host": "'$host'", "lets_encrypt": false, "http2https": true}'
