#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# clean up remote ns8 state
source /var/lib/nethserver/agent/environment
ns8-action cluster remove-external-domain $(printf '{"domain":"%s"}' "${USER_DOMAIN}")
ns8-action cluster remove-node $(printf '{"node_id":%d}' "${NODE_ID}")

# reset DB props
/sbin/e-smith/config setprop ns8 Host "" User "" Password "" TLSVerify enabled LeaderIpAddress ""
/sbin/e-smith/config setprop agent status disabled
/sbin/e-smith/config setprop wg-quick@wg0 status disabled Address "" RemoteEndpoint "" RemoteKey "" RemoteNetwork ""

# clean up agent state directory, preserving state/ directory
find /var/lib/nethserver/agent -not -name state -delete

# signal event
/sbin/e-smith/signal-event -j nethserver-ns8-migration-save
