#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

source /etc/nethserver/agent.env

app_id=${1:?Missing app_id argument}
app_sdir="${AGENT_STATE_DIR:?}/${app_id}"

#
# As alternative path to "bind/start, sync, finish", ensure the app state
# dir exists and toggle the file flag
#

mkdir -vp "${app_sdir}"
cd "${app_sdir}"

if [ -f skip ]; then
    rm -f skip
else
    touch skip
fi
