#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

source /etc/nethserver/agent.env
source "${AGENT_STATE_DIR}"/agent.env
source "${AGENT_STATE_DIR}"/environment

module=$1

if [ -z "${module}" ]; then
    echo "Usage: $0 <nethserver_module"
    exit 1
fi

source "${AGENT_STATE_DIR}/${module}/bind.env"

# Ensure endpoint is defined
: ${RSYNC_ENDPOINT:?}
export RSYNC_PASSWORD


ns8-action "cluster" remove-module '{"module_id": "'${MODULE_INSTANCE_ID}'", "preserve_data": false}'

rm -rf  "${AGENT_STATE_DIR}/${module}"
