#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#  //// delete file

# . /usr/libexec/nethserver/api/lib/helper_functions

# host=$(/sbin/e-smith/config getprop ns8 Host)
# user=$(/sbin/e-smith/config getprop ns8 User)
# password=$(/sbin/e-smith/config getprop ns8 Password)
# tls_verify=$(/sbin/e-smith/config getprop ns8 TLSVerify)
# tls_verify_arg=""

# if [ "$tls_verify" = "false" ]; then
#     tls_verify_arg="--no-tlsverify"
# fi

# /usr/bin/ns8-join "$tls_verify_arg" "$host" "$user" "$password"

# if [ $? -gt 0 ]; then
#     error "ConnectionExecuteFailed" "See /var/log/messages"
# fi
